# permissions for end users to edit helmaddonsresourcesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmaddonsresourceset-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmaddonsresourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmaddonsresourcesets/status
  verbs:
  - get
