# permissions for end users to view helmclusterresourcesetbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmclusterresourcesetbinding-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmclusterresourcesetbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmclusterresourcesetbindings/status
  verbs:
  - get
