# permissions for end users to edit helmclusterresourcesetbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmclusterresourcesetbinding-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmclusterresourcesetbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmclusterresourcesetbindings/status
  verbs:
  - get
