# permissions for end users to view helmaddonsresourcesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmaddonsresourceset-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmaddonsresourcesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - helmaddonsresourcesets/status
  verbs:
  - get
